### ISSUE TITLE
Hi.Can you tell the meaning of the 23 points in the skeleton? 

### ISSUE THREAD

**Issue by chenshuo0012** [mhy12345/Music-to-Dance-Motion-Synthesis#1]
I want to use this data , but I don't understand the meaning of 23 skeleton points, because there are 24 points in kinect.

**Comment by mhy12345** [comment]
We did not use KINECT to capture the skeleton points. Which means it is impossible for us to have the same data format as KINECT. As far as I know, these skeletons provided all major position of human motion. But if you need to use a public 3D model to fit the skeletons, maybe you need to re-calculate some position by yourself.
